### ISSUE TITLE
Doesn't work on older Rubies

### ISSUE THREAD

**Issue by dmcinnes** [Bluebie/digiusb.rb#1]
Hello,
I tried using this with the OS X system Ruby (1.8.7) and it installed fine but I got syntax errors when trying to run digiterm since you're using the 1.9-style hashes.

I cloned the project and changed the hashes to make it compatible, and after figuring out I needed to install libusb, I ran into another problem with io/console -- it's included in Ruby 1.9.3 though in previous versions there's an old gem that can be used. Unfortunately it doesn't work on the latest OS X.

To make a long story short, I think a requirement to use at least Ruby 1.9.3 would be good:

s.required_ruby_version = '>= 1.9.3'

Seems like a waste of time trying to get the io-console Gem to work with the latest OS X, it hasn't been touched in 3 years:
https://github.com/nobu/io-console

Using Ruby 1.9.3 works great!

**Comment by Bluebie** [comment]
agreed, it is only for ruby 1.9 and newer. I thought I mentioned as much in the readme but I'll add it to the gemspec like you said :)

**Comment by Bluebie** [comment]
And as a little sidenote I find it very annoying that Apple hasn't updated their system ruby since Tiger really. There was once a time when they advertised 'ruby on rails' support as a feature! At least we have homebrew ^_^

**Comment by dmcinnes** [comment]
Vintage Ruby :)

**Comment by Bluebie** [comment]
Aged to perfection? I think not. I like my json-style hashes.
