### ISSUE TITLE
Running digiterm on Raspberry Pi

### ISSUE THREAD

**Issue by svenroed** [Bluebie/digiusb.rb#4]
I hope you can help me out and maybe give me a hint what the problem might be. I am trying to connect a Digispark with my Raspberry Pi. I saw that you got it working. I tried the same way but I only get the following output.

Looking for Digispark running DigiUSB...
Attached to Digispark:?:@1.6
Type control + c to exit
/home/pi/.rvm/gems/ruby-1.9.3-p392/gems/libusb-0.3.2/lib/libusb/constants.rb:56:in `raise_error': LIBUSB::ERROR_ACCESS in libusb_open (LIBUSB::ERROR_ACCESS)
    from /home/pi/.rvm/gems/ruby-1.9.3-p392/gems/libusb-0.3.2/lib/libusb/device.rb:58:in`open'
    from /home/pi/digiusb.rb/lib/digiusb.rb:145:in `io'
    from /home/pi/digiusb.rb/lib/digiusb.rb:152:in`control_transfer'
    from /home/pi/digiusb.rb/lib/digiusb.rb:54:in `getc'
    from ./bin/digiterm:44:in`block in <main>'
    from ./bin/digiterm:43:in `loop'
    from ./bin/digiterm:43:in`<main>'

I seems like it can't find the right libusb library? 

I would be glad for any tips on this, I guess it's not a digiusb problem...

**Comment by Bluebie** [comment]
Have you tried running it with sudo? does it work when you do?

The only other bit difference I can see is that I am not using rvm - I have installed ruby 1.9 via apt-get in raspbian. I don't recommend anyone ever use rvm - it's a bunch of weird hacks which often don't work when you aren't running things from a terminal, and even when you are it can get pretty weird.

**Comment by Bluebie** [comment]
`sudo apt-get install ruby1.9.3` to get the same ruby I'm using on my pi. I know it works, because my house's doorbell depends on a pi running digiusb!

**Comment by svenroed** [comment]
yes! This is great. I removed the rvm install and installe via apt-get package manager. I also had to reinstall so gems but not it works great. 

Thank you so much, keep up with this good work!
